### ISSUE TITLE
Help Wanted: Undefined control sequence. 

### ISSUE THREAD

**Issue by chenboshuo** [Jinwen-XU/Q-and-A#1]
I use command
```
xelatex -output-directory="./build" Q-and-A-demo-ChatGPT-classical.tex 
```
and encounter the following errror:
```
(./build/Q-and-A-demo-ChatGPT-classical.aux)
*geometry* driver: auto-detecting
*geometry* detected driver: xetex

Package hyperref Warning: Rerun to get /PageLabels entry.

! Undefined control sequence.
<argument> \tl_gput_right:Ne 
                             \g_QA_content_tl {\exp_not:N \begin {QA_\l__QA_...
l.52 \end
         {document}
? 
! Emergency stop.
<argument> \tl_gput_right:Ne 
                             \g_QA_content_tl {\exp_not:N \begin {QA_\l__QA_...
l.52 \end
         {document}
No pages of output.
Transcript written on ./build/Q-and-A-demo-ChatGPT-classical.log.
```
I have installed `texlive` using
```
sudo apt install texlive-full 
```
and the version is
```
texlive-full is already at the latest version 2022.20230122-2
Nothing for Nala to do.
```
Could you give me some instruction to compile this demo `tex` file? Thank you for your attention.

**Comment by Jinwen-XU** [comment]
It seems that you are using an older version of this document class, but from the information you have provided I am not sure about this.

It might be better if you could provide the whole log file, so that I may see clearer which version of each package you were using.

**Comment by chenboshuo** [comment]
> It seems that you are using an older version of this document class, but from the information you have provided I am not sure about this.
> 
> It might be better if you could provide the whole log file, so that I may see clearer which version of each package you were using.

[Q-and-A-demo-ChatGPT-classical.log](https://gist.github.com/chenboshuo/92112f8d5c7afbd73ed409e290e4ea72) 
Thank you

**Comment by Jinwen-XU** [comment]
According to [Ulrike Fischer](https://tex.stackexchange.com/users/2388/ulrike-fischer) in her comment to [this question](https://tex.stackexchange.com/q/701910), you need to update your TeX distribution (notably `l3kernel`). Most of your packages still have the version before the release of TeX Live 2023.

Though it would seem proper for me to add a `\cs_generate_variant:Nn` for compatibility reason, from the next release (version `2023-11-21`) the newly added referencing feature would require the newest version `2023/11/01` of LaTeX2e anyway, so I shall not manually declare this variant.

**Comment by Jinwen-XU** [comment]
In the README and in the documentation, I have added the following message:

> **Attention:**
> For this document class to function properly, the LaTeX2e kernel must be at least as new as `2023/11/01`.

If this condition is fulfilled, then certainly your TeX distribution should be newly enough for the code to work properly.

Thank you for reporting this issue and for kindly providing your log file. If you encounter any further problem, feel free to reopen this issue or to open a new channel.

**Comment by chenboshuo** [comment]
> In the README and in the documentation, I have added the following message:
> 
> > **Attention:**
> > For this document class to function properly, the LaTeX2e kernel must be at least as new as `2023/11/01`.
> 
> If this condition is fulfilled, then certainly your TeX distribution should be newly enough for the code to work properly.
> 
> Thank you for reporting this issue and for kindly providing your log file. If you encounter any further problem, feel free to reopen this issue or to open a new channel.

Thank you for your reminder. I will go update my environment and  try again.
